### ISSUE TITLE
Найти, включить и протестировать usb ethernet в ядре freebsd

### ISSUE THREAD

**Issue by akovalenko** [mr-technologies/freebsd#2]
Теперь, когда freebsd грузится с диска, для удобства отладки и тестирования хорошо бы иметь к ней доступ  по ssh. Соответственно, пока мы отлаживаем драйвер mge, можно попробовать поднять сеть на usb-ethernet адаптере (как на plan9).

Сильно вкладываться в эту задачу не стоит: если при включении соответствующих драйверов адаптер с ходу не заработает -- оставляем его в покое.

**Comment by sniperrifle** [comment]
Сделано.
