### ISSUE TITLE
Сделать образ FreeBSD для РИКОРа

### ISSUE THREAD

**Issue by akovalenko** [mr-technologies/freebsd#7]
Сделать образ FreeBSD для РИКОРа

**Comment by akovalenko** [comment]
Похвала ядру, собранному sniperrifle вечером 3 декабря:

Я притащил обновлённое ядро на РИКОР (без переделки образа, через прямое копирование на FAT-раздел). С последними изменениями (убрана отладочная печать) оно стало дольше висеть при попытке поднять интерфейс без поллинга; зато если дождаться загрузки и поднять интерфейс в поллинге, _больше нет потерь пакетов и дублирования_.

```
root@rikor2:~ # mount -t nfs 10.10.0.12:/home/deployer/deploy/nfs/freebsd /mnt
root@rikor2:~ # /usr/bin/time cp /mnt/rootfs.tgz .
        1.69 real         0.00 user         0.55 sys
```

Как видим выше, файл размером 100MB скопирован по NFS за 1.7с реального времени. Это в общем-то успех.

Если отключить поллинг на работающем интерфейсе, всё _продолжает_ нормально работать.

Теперь надо сделать образ с этим ядром, причём поллинг форсированно включать в стартовых скриптах. Шурик, если его к понедельнику вечером не будет, я сам займусь. Дай знать, если есть вопросы.

**Comment by sniperrifle** [comment]
Та какой образ взял? Тот, что лежал на виртуалке? Я как раз тогда новый собрал и все там настроил как надо.
-rw-r--r--   1 builder  builder  1073741824 Dec  3 23:53 bsdroot.ufs

**Comment by akovalenko** [comment]
Образ не брал пока, заменил ядро в старом на ядро из нового.
Сейчас попробую записать образ целиком и загрузить.

**Comment by sniperrifle** [comment]
Окей, я там  поправил местонахождения рутфс и сделал дхцп.

**Comment by akovalenko** [comment]
А поллинг тоже включил? впрочем, скоро увижу

**Comment by sniperrifle** [comment]
И поллинг
ifconfig_mge0="DHCP polling" в /etc/rc.conf

**Comment by akovalenko** [comment]
Ага, вижу поллинг, несмотря на это, dhclient пока висит (думаю, скоро отвиснет).

Ещё я просил MAC-адрес фиксированный убрать из device tree, ты пробовал? вроде он сейчас там остался. Там какие-то проблемы?

**Comment by sniperrifle** [comment]
уберу щас и проверю что будет
не убирал, прошу прощения - из головы совсем это вылетело

**Comment by sniperrifle** [comment]
https://github.com/mr-technologies/freebsd/releases/tag/v1.0
